name: NASA Project CI
# Control when this workflow will run
on:
  push:
    # This workflow will be triggered when the code is pushed through one of these branches
    branches: [master]
    # To catch pull requests, where someone just pushes a change, so to trigger that
    pull_request:
      branches: [master]
jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checking the latest version
      - uses: actions/checkout@v3
      # Check whether node is setup and installed
      - name: Use Node.js version 16
        uses: actions/setup-node@v3
        # Telling the version of the node ourself
        with:
          node-version: "16"
      - run: npm install
      # For client also we have to run our build
      - run: npm run build --prefix client
