
name: NASA Project CI
on:  # Control when this workflow will run
  push:  # This workflow will be triggered when the code is pushed through one of these branches
    branches: [ main ]
  pull_request:  # To catch pull requests, where someone just pushes a change, so to trigger that
    branches: [ main ]
jobs:
  build:
    env:
      CI: true #create-react-app test script will know that we are running in CI env, and disable watch mode
      MONGO_URL: mongodb://localhost/nasa
    strategy: #We can run our tests and jobs in different env by this strategy option
      matrix: #It will give us options of these under below
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   # Checking the latest version
      - name: Use Node.js version ${{ matrix.node-version }}  # Check whether node is setup and installed
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run build --prefix client   # For client also we have to run our build
      - run: npm test
